### ISSUE TITLE
Makes no sense and made things worse! and KSP UNPLAYABLE!

### ISSUE THREAD

**Issue by neil501** [net-lisias-ksp/randon-rants-from-clueless-users#1]
I downloaded and installed this and now ksp dont work it says i have other copies of mod manager but this is the only one ive downloaded. Looks like all these files just bunched together with no real explanation of what each file is and does. I'm deleting this and forgetting this junk ever existed! Terrible program! trying to make things easier but in the process breaks the game!

**Comment by Lisias** [comment]
Github doesn't tracks the source of the issue!

Oh well.. This has beed opened on https://github.com/net-lisias-ksp/ModuleManager and moved here to avoid cluttering te issue tracking with useless rants. ;)
