### ISSUE TITLE
nightmare

### ISSUE THREAD

**Issue by blooze2gh** [net-lisias-ksp/randon-rants-from-clueless-users#3]
creates a module manager NIGHTMARE!!!!!!

**Comment by Lisias** [comment]
This has been opened on https://github.com/net-lisias-ksp/ModuleManager and moved here to avoid cluttering the issue tracking with useless rants. ;)

**Comment by Lisias** [comment]
Oh, hell. I will answer to this:

## Sweat Dreams, baby! :)
